include:
  - .cnb/workflows/sync-github-main.yml
  - .cnb/workflows/pr-check.yml

$:
  vscode:
    - docker:
        image: docker.cnb.cool/wwvo/dev-env/python:latest
      services:
        - vscode
        - docker
